### ISSUE TITLE
Some problems with createuser.php 

### ISSUE THREAD

**Issue by nikorafu** [therecluse26/PHP-Login#100]
There is message appear on the browser here 
"Fatal error: Can't use function return value in write context in C:\xampp\htdocs\PHP-Login-master\login\createuser.php on line 37"

Please kindly teach me how may I fix them. Sorry, I am very beginner programming.
Thank you in advance!

**Comment by therecluse26** [comment]
Hi, did you add anything to the code? If so, could you please post that
page's code for me? Thanks.

You might want to use the dev branch version for now, it's been drastically
updated from this version, just fyi.

**Comment by koenschuite** [comment]
Having the same problem here, not sure how to fix it? Does it have to do with the config settings?

**Comment by comconet** [comment]
What is the dev branch version?  I noticed also someone used an installer to setup the login.php.  Please send the link to it.  - Rolfe

**Comment by therecluse26** [comment]
Pull the dev branch (on my fork) in using this command in your command
line: git clone -b dev https://github.com/therecluse26/PHP-Login.git

There are still a few bugs with the installer (but it might work just fine
for you, ymmv) on certain platforms, but the base platform is functioning
properly and has quite a few more features than the master branch. Hope
that helps! Basically, once you clone that, navigate in your web browser to
http://{base-directory-of-project}/install/index.php to start the
installation process
