### ISSUE TITLE
Error when installing Dev Branch

### ISSUE THREAD

**Issue by DSMTurboAWD** [therecluse26/PHP-Login#102]
I am having trouble understanding what is happening when I am installing this using the built-in installer script.
I am using ampps to prototype this before I deploy it to a webserver.
I think where it is choking is on the modified port I am using (port 81) instead of port 80
So, when installing, it should be localhost/dev/login/install
![image](https://user-images.githubusercontent.com/2649649/29046080-8bfa110a-7b8b-11e7-9960-e1e21d59d20e.png)

However I do get an error right at the end of the install process:
![loginerrors](https://user-images.githubusercontent.com/2649649/29046288-6b84af42-7b8c-11e7-923c-9e347b33dbf9.PNG)

From what I can tell digging into the code, it is either something to do with the PORT or an issue with the root install path, which by default, wanted to be C:\Program. (global variable 'base_dir')
I am not sure if that should be C:\Program Files (x86)\ampps\... etc or what
I assume this will likely work fine on a hosted platform without issue, but wanted to be sure I am not missing something before I go an try to deploy it to my web server.

NOTE: I have not modified any of the files. This is a pure CLONE, uploaded to my localhost
using PHP 5.5

**Comment by VA7NFH** [comment]
I think you difficulty is because you included the installer path in base url. If you change base url to http://localhost/website/ it should work.

**Comment by therecluse26** [comment]
Yeah, also add the modified port to your base url, so
http://localhost:81/website

**Comment by DSMTurboAWD** [comment]
So, I have beat this up some more, I feel like I am getting closer, but the base install path I think is what is getting me
Again, I am using Ampps installed locally:

***C:\Program Files (x86)\Ampps\www\Website\login\***
is where the actual files live

**http://localhost:81/Website/login/install/install.php**
Is the URL I am using to fun the installer

These are the settings I am using
![screencap02](https://user-images.githubusercontent.com/2649649/29052377-4de6d758-7baf-11e7-8a37-2262f97adac3.PNG)

also, swapping the URL and root install yield the same results
Root = / 
base URL = localhost:81/Website/login

This is a loot at the directory structure outside of the project view 
![screencap01](https://user-images.githubusercontent.com/2649649/29052370-3794d8ce-7baf-11e7-9a79-244dbd5f3606.PNG)

This is the error on the install page
![screencap](https://user-images.githubusercontent.com/2649649/29052396-683b747e-7baf-11e7-8d92-194c355cee41.PNG)

This is if I then try to ping the index page after (Which looks the same as the above screen)
![screencap03](https://user-images.githubusercontent.com/2649649/29052401-70a9f068-7baf-11e7-96dc-44c96386ff96.PNG)


I realize this is a Dev branch, and that is cool, I just wish I could figure out how to change the values or what it is looking at. I took a look at the DB config and that looks right (and connects and everything). I could try to put something in that will bark at the console, but I have not looked through the code enough to be able to do that.

I was able to get the release code to work just fine

**Comment by DSMTurboAWD** [comment]
This may have to do with my PHP version, I am going to derp with it some more and if I need, revisit this issue
