### ISSUE TITLE
404 Problems "scripts/PHPMailer/PHPMailerAutoload.php" not found and request 

### ISSUE THREAD

**Issue by dimitrihtml** [therecluse26/PHP-Login#106]
hello there I really like this form so easy to install and use directly, but I had a few problems with it and I hope there is an answer for these problems 
1-i'm not able to add user manually via database, when I click insert (to add users) every thing looks good but it looks like the password is in varchar and  when I enter any numerical password it does not accept it also I was hoping to show the actual password of the user and not bunch of code (numbers and letters) ]
2-when I sign up I never receive an email for activation, it was showing an error for 404 (file missing) in this directory 'scripts/PHPMailer/PHPMailerAutoload.php' and I checked and there is a file missing in that directory I hope that someone can solve this 
3-(request) I want every user registered to go to a different page from other users (I'm creating students database and I want for every student to show his info only and his grades in the index.php file)

**Comment by Gerrymandered** [comment]
I have the same problem with the second issue

**Comment by brianjcollins** [comment]
#112 

Look at my comment to see if it applies to your scenario.  @Gerrymandered

**Comment by bbashel1** [comment]
@brianjcollins I have downloaded and cloned, in both ways, I am getting same error #112
