### ISSUE TITLE
can't verify when creating a new account

### ISSUE THREAD

**Issue by louisejoy** [therecluse26/PHP-Login#110]
i'm not getting any email when i'm creating an account, i got it connected to the database and what i think the problem, is the PHPmailer folder. It's empty when i downloaded the PHP-login-lockout.zip file but i looked around and found the PHPmailer.zip so i download that and extracted it to the empty PHPmailer folder. But it's still not sending any email.. sorry i'm still new to this site so pls tell me if i'm missing something

**Comment by louisejoy** [comment]
![screenshot 112](https://user-images.githubusercontent.com/30917477/29761031-bb067398-8bf9-11e7-9d1e-1e9a98994725.png)

**Comment by EmanuelM** [comment]
Did you configured the PHPMailer in the _"login/config.php"_ file?

**Comment by TijsDeBelie** [comment]
After configuring the phpmailer with all the corrct settings, it still doesn't send an email
