### ISSUE TITLE
PHPMailerAutoload.php

### ISSUE THREAD

**Issue by bbashel1** [therecluse26/PHP-Login#112]
Warning: require(PHPMailerAutoload.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/PHP-Login/login/includes/mailsender.php on line 6  Fatal error: require(): Failed opening required 'PHPMailerAutoload.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/PHP-Login/login/includes/mailsender.php on line 6

**Comment by brianjcollins** [comment]
I'm assuming you downloaded the zipped distribution for PHP-Login, vs cloning with git.  PHPMailer is only a symbolic link and won't be included in the zipped file.  If you look at the install instructions is specifically tells you to clone recursively.

[https://github.com/fethica/PHP-Login#clone-the-repository-recursively-to-include-php-mailer-submodule](url)

**Comment by bbashel1** [comment]
@brianjcollins thank you so much.

**Comment by WELSCHH** [comment]
Hello! I downloaded it by cloning with git, but it still won't download the phpmailerautoload.php.

**Comment by therecluse26** [comment]
FYI, version 3 relies on Composer to pull dependencies, so recursive cloning is no longer necessary, just run `composer install` in the project root
