### ISSUE TITLE
PHP Fatal error:  Call to undefined function password_hash() in login/createuser.php on line 8

### ISSUE THREAD

**Issue by scumola** [therecluse26/PHP-Login#129]
Looks like password_hash was created in php 5.5.0 ( http://php.net/manual/en/function.password-hash.php ), should make 5.5.0 a requirement for using this package.

**Comment by therecluse26** [comment]
I've upped the requirement to version 7 for various technical reasons, plus it's around 3 years old at this point, so I figured not too crazy for new projects ;)
