### ISSUE TITLE
How do I exactly configure the email settings?

### ISSUE THREAD

**Issue by raul4740** [therecluse26/PHP-Login#135]
i added my own email address on the $from_email var. I really dont know if that is right, but emails arent arriving so i cant activate accounts.

**Comment by shaunrc493** [comment]
You'll need to configure the SMTP settings under config.php. However I found it easier to use the PHP mail() function.

Which part is it you're having trouble with? Is it the createuser.php and signup.php files?

**Comment by raul4740** [comment]
Not sure with which file. I tried modifying config.php and setting a gmail account but no email is recieved. The GUI showed no error message when I registered and it was added to the database.

**Comment by shaunrc493** [comment]
When creating a new user you are using the signup.php file. This then posts to the createuser.php file to do all the mailing and database handling. I had the same problem I think you're having where they were added to the database but not receiving emails. Try updating your createuser.php file to this:

(Starting from line 50)
`//Send verification email
            // $m = new MailSender;
            // $m->sendMail($newemail, $newuser, $newid, 'Verify');
            
            $to1 = "admin email address";
            $to2 = $newemail;
            $subject = "Welcome, $newuser";

            $txt1 = " email to admin ";
            $txt2 = " email to new user ";
           
            mail($to1, $subject, $txt1);
            mail($to2, $subject, $txt2);

            //mail($newemail, $newuser, $newid, 'Verify');

        } else {
            //Failure
            mySqlErrors($response);`

**Comment by shaunrc493** [comment]
Anything that is commented out isn't needed, I just left mine in so I could see my work flow

**Comment by raul4740** [comment]
So I need to modify both config.php and createuser.php?
I dont know what am I doing wrong 
![imagen](https://user-images.githubusercontent.com/25697932/32300898-3b4302ce-bf21-11e7-9620-52f2d737231e.png)

![imagen](https://user-images.githubusercontent.com/25697932/32300954-6ec1e822-bf21-11e7-97b3-f153a2d01e21.png)
 
and I am getting a warning now

![imagen](https://user-images.githubusercontent.com/25697932/32301022-b5fae680-bf21-11e7-86da-f4a1e897ca86.png)

**Comment by therecluse26** [comment]
Hi @raul4740 , I pushed major updates a couple of days ago that should take a lot of the headache out of email config. Try cloning the master branch now and seeing if you can get it working more easily now. There are a bunch of new features and security patches as well, so you may want to upgrade regardless, thanks :)
