### ISSUE TITLE
Verification page

### ISSUE THREAD

**Issue by shaunrc493** [therecluse26/PHP-Login#136]
Hi,
Absolutely loving this project here and I'm just trying to add a few extra things. I couldn't get the verification to work how it has been set in the project so what I've done instead added 2 mail() 's to the create user page.

One mail() sends the admin an email to notify them when a new user is created, just for records and satisfaction. The second mail() sends to the user to welcome them to the site and asks them to use their activation code (the password hash) to verify their account by following the link provided.

Everything has gone well so far but now the when I enter the information ($accemail and $activation) into the form I get the error saying 'Wrong username or password' which is part of the session data as far as I can tell. I have tried to destroy the session and also comment it out but neither have the desired effect.

The form also registers an entry into the attempted login database.

Anyone that might be able to help please let me know and I'll show you the appropriate files!

Thank you!

**Comment by cdmarioe** [comment]
I want to do something like that, in the admin email to recieve the new user info, like username and password, can you help me?

**Comment by shaunrc493** [comment]
The way I did that @cdmarioe was send the email via phpmail, or mail(), then set the variables for mail as mail($to, $subject, $txt)

$to is their email address which you can link to the array, subject is whatever you want and in the $txt you can call other arrays such as the username and password.

When I get home from work I can help properly. Hope this helps for now

**Comment by therecluse26** [comment]
Hi @shaunrc493 and @cdmarioe , I pushed some major updates a couple of days ago that should fix a lot of the problems you're having. Try cloning the master branch now and seeing if you have similar problems.

Also, I do plan on adding support for different mailing methods in future updates, just FYI.
