### ISSUE TITLE
i do not receive verification in my email

### ISSUE THREAD

**Issue by kon777** [therecluse26/PHP-Login#137]
i use git clone --recursive https://github.com/fethica/PHP-Login.git 

i made mysql database with 2 tables

i configure dbconf.php with my mysql username, mysql password and databasename

i configure config.php, $from_email: my yahoo email
$from_name: my name
$smtp_server : smtp.mail.yahoo.com 
$smtp_user: my yahoo email
$smtp_pw: my yahoo password 
$smtp_port: 465 
$smtp_security: ssl

after i sign up, it says "Thank you for signing up! You will receive an email shortly confirming the verification of your account."

i do not receive verification in my email
what i want is to receive verification in my email

**Comment by shaunrc493** [comment]
You may need to check your yahoo settings to allow emails to be sent a received by external software. If that doesn't work also try a mail client (not browser)

**Comment by shaunrc493** [comment]
Try #135

**Comment by Blaatbok** [comment]
The folder under scripts\PHPMailer is empty, I think that's the problem. Can you check if you got files in that folder?

**Comment by shaunrc493** [comment]
Yes the PHPMailer folder is empty as the MASTER version is an incomplete project. The DEV updates a lot of features so you might want to check that out too.

Using the PHP mail() function works without the automailer functions written into this project. Be aware though that the PHP mail() uses your daily allowance in your host.

I'm currently using 000webhost for my website and it works nicely on that but I only get 50 (maybe 60) emails a day. By paying for a host however you can get anything between 50 emails per hour and upwards of 200 an hour!

Are you hosting your websites or running them through localhost?

**Comment by Blaatbok** [comment]
I'm hosting the website and i'm using the Office365 SMTP to send my e-mail. I get the following error in the log file:

[30-Oct-2017 18:59:38 Europe/Amsterdam] PHP Fatal error:  require(): Failed opening required 'scripts/PHPMailer/PHPMailerAutoload.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/sna1qd/public_html/web/login/includes/mailsender.php on line 6

**Comment by shaunrc493** [comment]
`<?php
/**
* Blah blah
*/
class MailSender extends AppConfig
{
    public function sendMail($userarr, $type)
    {
        $resp = array();
        require $this->base_dir.'/login/vendor/phpmailer/phpmailer/PHPMailerAutoload.php';

        /* ADD $_SERVER['SERVER_PORT'] TO $verifyurl STRING AFTER $_SERVER['SERVER_NAME'] FOR DEV URLS USING PORTS OTHER THAN 80 */

        //ADD sendmail_path = "env -i /usr/sbin/sendmail -t -i" to php.ini on UNIX servers

        $mail = new PHPMailer;
        $mail->isHTML(true);
        $mail->CharSet = "text/html; charset=UTF-8;";
        $mail->WordWrap = 80;
        $mail->setFrom($this->from_email, $this->from_name);
        $mail->AddReplyTo($this->from_email, $this->from_name);

        //SMTP Settings
        if ($this->mail_server_type == 'smtp') {

            $mail->IsSMTP();
            $mail->SMTPAuth = true;
            $mail->Host = $this->mail_server;
            $mail->SMTPSecure = $this->mail_security;
            $mail->Port = $this->mail_port;
            $mail->Username = $this->mail_user;
            $mail->Password = $this->mail_pw;
            $mail->SMTPDebug = 2; //Leave this set to 2; mail debug gets logged to mail_log db table

            $mail->SMTPOptions = array(
                'ssl' => array(
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                )
            );
        }

        if ($type == 'Verify') {

            $admins = UserData::adminEmailList();

            foreach($userarr as $usr){

                $uid_64 = base64_encode($usr['id']);

                $verifyurl = $this->base_url . "/login/verifyuser.php?v=1&uid=" . $uid_64;

                $mail->AddBCC($usr['email'], $usr['username']);

                if ($this->admin_verify == 'true') {

                    foreach ($admins as $admin) {
                        $mail->AddBCC($admin['email'], $usr['username']);
                    }
                }
            }

            include $this->base_dir."/login/partials/mailtemplates/verifyemail.php";

                //Set the subject line
                $mail->Subject = $usr['username']. ' Account Verification';

                //Set the body of the message
                $mail->Body = $verify_template;

                if ($this->admin_verify == true) {
                    $mail->AltBody = $this->verify_email_admin;
                } else {

                    $mail->AltBody = $this->verify_email_noadmin . $verifyurl;
                }

            } elseif ($type == 'Active') {


                foreach($userarr as $usr){

                    $mail->AddBCC($usr['email'], $usr['username']);

                }

                include $this->base_dir."/login/partials/mailtemplates/activeemail.php";

                //Set the subject line
                $mail->Subject = $this->site_name . ' Account Created!';

                //Set the body of the message
                $mail->Body = $active_template;

                $mail->AltBody  =  $this->active_email . $this->signin_url;

            };

        try {

            //Sends email and logs the response to mail_log table
            ob_start();
            $status = $mail->Send();
            $debugMsg = ob_get_contents();
            ob_get_clean();
        EmailLogger::logResponse($debugMsg, $usr, $type, $status);

            $resp['status'] = true;
            $resp['message'] = '';

            return $resp;

        } catch (phpmailerException $e) {

            $resp['status'] = false;
            $resp['message'] = $e->errorMessage();

            return $resp;

        }
    }

    public function sendResetMail($reset_url, $to_email, $username) {

        $resp = array();
        require $this->base_dir.'/login/vendor/phpmailer/phpmailer/PHPMailerAutoload.php';

        try {

        $mail = new PHPMailer(true);
        $mail->isHTML(true);
        $mail->CharSet = "text/html; charset=UTF-8;";
        $mail->WordWrap = 80;
        $mail->setFrom($this->from_email, $this->from_name);
        $mail->AddReplyTo($this->from_email, $this->from_name);

        //SMTP Settings
        if ($this->mail_server_type == 'smtp') {

            $mail->IsSMTP(); //Enable SMTP
            $mail->SMTPAuth = true; //SMTP Authentication
            $mail->Host = $this->mail_server; //SMTP Host
            //Defaults: Non-Encrypted = 25, SSL = 465, TLS = 587
            $mail->SMTPSecure = $this->mail_security; // Sets the prefix to the server
            $mail->Port = $this->mail_port; //SMTP Port
            //SMTP user auth
            $mail->Username = $this->mail_user; //SMTP Username
            $mail->Password = $this->mail_pw; //SMTP Password
            //********************
            $mail->SMTPDebug = 0; //Set to 0 to disable debugging (for production)

            $mail->SMTPOptions = array(
                'ssl' => array(
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                )
            );
        }

        $mail->AddBCC($to_email, $username);


        //Set the subject line
        $mail->Subject = $this->site_name . ' Password Reset';

        include $this->base_dir."/login/partials/mailtemplates/resetemail.php";


        //Set the body of the message
        $mail->Body = $reset_template;
        $mail->AltBody = $this->reset_email . $this->signin_url;

        //Sends email and logs the response to mail_log table
        ob_start();
        $status = $mail->Send();
        $debugMsg = ob_get_contents();
        ob_get_clean();

        $emailToLog = array("email"=>$to_email);

        EmailLogger::logResponse($debugMsg, $emailToLog, 'Password Reset', $status);

        $resp['status'] = true;
        $resp['message'] = "Password reset sent! Check your email";
        return $resp;


        } catch (phpmailerException $e) {
            $resp['status'] = false;
            $resp['message'] = $e->errorMessage();
            return $resp;

        } catch (Exception $e) {
            $resp['status'] = false;
            $resp['message'] = $e->getMessage();
            return $resp;
        }
    }
}
`

**Comment by shaunrc493** [comment]
mailsender.php from the DEV version.

Try saving that into the required area and see if that helps

**Comment by Blaatbok** [comment]
I Cloned it recursivly with git, my problem is solved now.

Thank you.

**Comment by shaunrc493** [comment]
Hope it helped! 👍

**Comment by kon777** [comment]
i can receive email now with word Verify and my id when i add mail($newemail, $newuser, $newid, 'Verify'); 
below of //Send verification email
$m = new MailSender;
$m->sendMail($newemail, $newuser, $newid, 'Verify'); in createuser.php

how can i activate my account that i register if the email do not give me link and also do not show how to activate my account? peace.

**Comment by kon777** [comment]
php mail() or @mail() function works nicer than smtp. here is tutorial: https://www.tutorialrepublic.com/php-tutorial/php-send-email.php .

**Comment by kon777** [comment]
php mail() or @mail() function works nicer than smtp. here is tutorial: https://www.tutorialrepublic.com/php-tutorial/php-send-email.php . peace.

**Comment by kon777** [comment]
php @mail() or mail() function works nicer than smtp. https://www.tutorialrepublic.com/php-tutorial/php-send-email.php. peace.
