### ISSUE TITLE
Recieve email notification when new account is created

### ISSUE THREAD

**Issue by cdmarioe** [therecluse26/PHP-Login#138]
How can i recieve email notification when new account is created, the user and password?

**Comment by shaunrc493** [comment]
Inside login/createuser.php try this:

 
            if ($response == 'true') {

            echo '<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'. $signupthanks .'</div><div id="returnVal" style="display:none;">true</div>';

            $to1 = "example@adminemail.com";
            $to2 = $newemail;
            $subject = "Welcome, $newuser";
            
            $txt1 = "
            A new user has just created an account!
            
            Their details are:
            ----------------------
            USERNAME: $newuser
            PASSWORD: $pw1
            E-ADDRESS: $newemail
            -----------------------
                      
            Admin";

            $txt2 = "
            $newuser,

            Your account has been created. Verify some stuff....

            Admin";
           
            mail($to1, $subject, $txt1);
            mail($to2, $subject, $txt2);
            
             } else {
            //Failure
            mySqlErrors($response);

**Comment by cdmarioe** [comment]
Thanks, 
i had to put it into login/mailsender.php, that's how it works...

**Comment by therecluse26** [comment]
@
