### ISSUE TITLE
SESSION variables

### ISSUE THREAD

**Issue by shaunrc493** [therecluse26/PHP-Login#142]
Has anyone been able to add extra session variables?

I'm wanting to add the user's email address and verification INT to the SESSION data too.

I've read up a few things but I can't seem to get it to work.

Cheers!

**Comment by therecluse26** [comment]
Hi @shaunrc493 , sorry so late with this, I've been very busy lately and am just now getting to responding to a lot of these issues. For starters, try cloning the new update that I pushed last night, it includes a ton of new features and is more secure. 

Secondly, if you definitely want to add more session variables (in the new version), you would edit the `/login/class/loginhandler.php` file right under line 63. 

Also, closing this just to empty out the inbox a bit, but if you require more assistance, feel free to re-open this issue. Thanks!
