### ISSUE TITLE
bootstrap 4

### ISSUE THREAD

**Issue by Razzo1987** [therecluse26/PHP-Login#147]
Hi,
I try to use this code with bootstrap 4.
The CSS work correctly, but I have come problem with the JS because if i use your **jquery-2.2.4.min.js** instead **code.jquery.com/jquery-3.1.1.slim.min.js** it work coccetly.

can you update the jquery version?

thanks

**Comment by therecluse26** [comment]
I haven't verified that this will work, but most of the jQuery classes that I use should be consistent across all versions 2 and up. I would guess that you'd be okay, but you may want to try it just to see.

Also, I just pushed out a big update with a lot more features, so you may want to update to that before trying. If you do go this route, the file you'll need to change is `/login/partials/libincludes.php`
