### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by ClarkyKent** [therecluse26/PHP-Login#148]
I keep getting this error on master branch  and on dev branch as well.
On dev branch i was able to install everything fine. I can login to admin account.  But if i want to create an account i get thi "internal server error" as soon as i click signup button.

What i am doing wrong. Please help!

**Comment by therecluse26** [comment]
Hey @ClarkyKent , I was just doing some updates last night that may have fixed this issue. Try cloning the main branch now and giving it a try and let me know if you're still having this error.

**Comment by ClarkyKent** [comment]
hey, @therecluse26 
I did pull after you merged the dev branch to master.
Now it is working for me. 
Thanks
