### ISSUE TITLE
After auto-install, admin pages are unstyled and buttons are not functioning

### ISSUE THREAD

**Issue by romanmke** [therecluse26/PHP-Login#149]
After auto-install, which was successful admin pages are unstyled and buttons are not functioning.

Please advise.

**Comment by therecluse26** [comment]
Does your web host allow shell access?
  

  
  

  
  
>

**Comment by romanmke** [comment]
I am using a local install of XAMPP, let me check.

**Comment by therecluse26** [comment]
It sounds like composer didn’t properly pull dependencies in during the install (the automated installer invokes composer in the shell using a popen command). Try navigating to PHP-Login’s root folder in a terminal and running “composer install” (after downloading composer of course)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by romanmke** [comment]
Ill give it a shot, thank you!

**Comment by therecluse26** [comment]
No problem! Let me know how it goes 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by romanmke** [comment]
Good call,
All seems to be working ATM.

Thank you for this by the way!

**Comment by therecluse26** [comment]
Awesome, glad we could get it up and running, and happy to help!
