### ISSUE TITLE
Error xER41300

### ISSUE THREAD

**Issue by CraziManiah** [therecluse26/PHP-Login#150]
When I log in I receive this error.
Server Error: Please contact site administrator at *******@gmail.com and relay this error - xER41300

**Comment by R1NTS1** [comment]
@CraziManiah  Read the 4th comment.
https://github.com/therecluse26/PHP-Login/issues/93

**Comment by R1NTS1** [comment]
I have almost the same problem. 
When i use my SMTP settings, it's make my website loading too slow.

**Comment by therecluse26** [comment]
The core functionality of the login system requires a working email server.
If you can't make a connection to your mail server through the site config,
this error will continue to pop up.

**Comment by CraziManiah** [comment]
Thanks for that. Should be easier for other people to find this aswell, if they ever have this issue.

**Comment by Uwe-MrT** [comment]
Hi,
i use smtp starttls on port 25 on my linux server with self signed certs.
Outlook says - self signed cert. but if i click ok i can send mails until i restart outlook.
Thunderbird accept smtp starttls on port 25. i can send mails.
but the config site of the php login site does not accept these settings.
Can i fine tune something on the mailhandler.php.txt file ?
it sends me Account Verification mails, but on config site i get an error.
Server Error: Please contact site administrator at (my-mail-adress) and relay this error - xER41300

**Comment by Uwe-MrT** [comment]
ok now everything works fine, but i always have the error banner
Server Error: Please contact site administrator at (my-mail-adress) and relay this error - xER41300
maybe because i login to smtp with a name - not with an email adress ?
can i disable this message ?
