### ISSUE TITLE
How to integrate this to mysite?

### ISSUE THREAD

**Issue by Killa8** [therecluse26/PHP-Login#151]
Great script, works perfectly, tho there was a small css/js directory issue.
Now i'l like to know how to integrate it to work with my website (sorry if it sounds silly to ask).
Hope to get a reply soo :)

**Comment by Killa8** [comment]
Moved to UserSpice
Way better

**Comment by therecluse26** [comment]
Good to know, thanks for sharing   
  

  
  

  
  
>
