### ISSUE TITLE
Vendor scripts not in download

### ISSUE THREAD

**Issue by abdelouali** [therecluse26/PHP-Login#154]
Hi, 

I successfully installed the script but the vendor script are missing.

![image](https://user-images.githubusercontent.com/13354388/34592788-dd337c8a-f1c6-11e7-8bc4-8910e2a90941.png)

**Comment by abdelouali** [comment]
I also get this error code xER41300

**Comment by therecluse26** [comment]
The missing vendor files mean that installation most likely failed the
composer step. Are you hosting on a VPS or some other way? If you have
shell access, navigate to the root directory of php-login and run `composer
install` (and make sure that you have read/write permissions on that
directory).

And the `xER41300` error means that your mailer wasn't able to authenticate
with an smtp server. You can configure that in the Edit Config menu under
the `mailer` section

**Comment by abdelouali** [comment]
Thank you! I fixed this by chmod the folder and subfolders where the install script is placed. Chmod to 777 and it will be fixed.
