### ISSUE TITLE
CSS Styling not working

### ISSUE THREAD

**Issue by ZaakaJarimbo** [therecluse26/PHP-Login#155]
I have just gone through the install (automated) and have no CSS styling, it is a vanilla install on WAMP64

**Comment by ZaakaJarimbo** [comment]
Tried attaching a screengrab but did not work

**Comment by ZaakaJarimbo** [comment]
Error Code xER41300

**Comment by pepsimatt** [comment]
Check for 404 errors on your bootstrap.min.css, bootstrap.min.js & jquery.min.js files. It appears they didn't include them. Just download the latest versions of each yourself, worked for me.

**Comment by n0tj** [comment]
@pepsimatt Could you expand on that? I'm having the same issue.

**Comment by pepsimatt** [comment]
@n0tj View your source & click all of these links: bootstrap.min.css & bootstrap.min.js & jquery.min.js
You'll see they all 404.  You need to download them yourself (google them). Then put them in the corresponding path/folder (which also needs to be created).

**Comment by therecluse26** [comment]
@n0tj You should run `composer install` at the root of the install directory from a command line, that should pull in all necessary dependencies.
