### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by johnny68** [therecluse26/PHP-Login#156]
I'm currently trying to install this in my google cloud VM instance.
![automated](https://user-images.githubusercontent.com/16421516/34765529-c0b53968-f617-11e7-89b2-359ddce05f7b.PNG)
But is giving me these errors.
Can anyone help me ?
I have manually set the directory permissions to 777.
Is there something that I'm forgetting.

**Comment by therecluse26** [comment]
Sorry I never got back to you (the life of an open source developer gets busy). Did you ever get this to work? If not, I just released a new version, you might want to try giving it another go?
