### ISSUE TITLE
Error in admin/maillog.php

### ISSUE THREAD

**Issue by Abysmal** [therecluse26/PHP-Login#168]
PHP Warning:  Illegal string offset 'rowcount' in ../admin/maillog.php on line 16
PHP Warning:  Illegal string offset 'rowcount' in ../admin/maillog.php on line 22

**Comment by therecluse26** [comment]
How did you install this? Did you maybe run into any errors during the install process? All of those tables should be created automatically in both the automated installer and the manual installation cases.

**Comment by Abysmal** [comment]
The database was a manual create and install because I was getting errors creating the triggers..  Being on a shared cpanel host, the DB users are all prefixed with the owner name ie: "xxxxxxxx_<admin_user>" but the auto install assigns the triggers to the 'root@localhost' so I have to change them..  But the db setup sql is what created the tables..

k.

**Comment by therecluse26** [comment]
Thank you! I hope it serves you well :) 

I also didn't notice that those definers were requiring the root user. I don't think a ton of people have been using the manual method that I'm aware of, so you're the first person to point that out to date. Let me see what I can come up with for that and get back to you.

**Comment by Abysmal** [comment]
It does it with the automated install as well unless I pre-change the file..

**Comment by therecluse26** [comment]
Which file are you pre-changing? I'm not seeing that issue in the automated
install scripts anywhere. For the manual installer, I just lazily generated
and edited the scripts output by MySQL, so it included that extra line for
adding a "DEFINER" for the triggers, but those don't exist anywhere in the
automated script

**Comment by Abysmal** [comment]
Let me know how I can help..

**Comment by Abysmal** [comment]
I would have to look which file i had to change... I had a few failures..  I guess I should pay more attention.. and record everything..

**Comment by therecluse26** [comment]
Ok, I just pushed the change that removes the root user restriction, so
pull those in and try restarting the install process

**Comment by Abysmal** [comment]
Okay.. will try again over the weekend

**Comment by Abysmal** [comment]
I just installed and tested with the latest version and All works as expected. I used the Automatic Installation.
