### ISSUE TITLE
MySQL said: Documentation  #1231 - Variable 'sql_mode' can't be set to the value of 'NULL'

### ISSUE THREAD

**Issue by ravi503** [therecluse26/PHP-Login#174]
/*!50003 SET sql_mode              = @saved_sql_mode */

**Comment by therecluse26** [comment]
@ravi503  You can just remove that line entirely and it should be alright. I'll try to remove it from my end as well. Lines like that were auto-generated by MySQL create scripts, and I haven't cleaned all of the irrelevant ones out fully, so thanks for pointing that out!
