### ISSUE TITLE
Installation Stuck at 95%

### ISSUE THREAD

**Issue by michaelv1992** [therecluse26/PHP-Login#176]
Hi,

When I use the installer, it gets stuck at 95%.
Downloading composer.phar is the last line thrown. Everything seems to work fine up until that point.

**Comment by therecluse26** [comment]
Hi @michaelv1992 , you should be able to proceed manually from there, as that's the last step. If you don't already have composer, download it ( https://getcomposer.org/download ), use your terminal to navigate to your php-login site root and run `composer install` and that should finish the installation for you. Then just go ahead and login as your superadmin account and edit your site config as normal.
