### ISSUE TITLE
How to run the webbased composer with manual install

### ISSUE THREAD

**Issue by TheBroTMv2** [therecluse26/PHP-Login#183]
How to run the webbased composer with manual install? My problem is i have no shell access and in your doc is a webbased composer or something like that mentioned but how can i run that manual?

**Comment by obieito** [comment]
I have the same problem... Would be great to bypass the shell access, I can't have it either for the project where I'd like to use PHP Login =/

**Comment by therecluse26** [comment]
Sorry, there really is no way that I'll be able to support that doesn't require shell access. Like I said, you could maybe try to do it on your development machine and then copying the entire directory up to your webserver. (there's a new version I just released, by the way!)
