### ISSUE TITLE
superAdmin does not work?

### ISSUE THREAD

**Issue by Xirez** [therecluse26/PHP-Login#184]
Hello, thank you for providing this repository!

I do however have a problem, i have used the automatic installer, everything seems to work, except the super admin role. Wich makes me unable to configure the last stape of the installer.
Aswell as all the bootstrap is broken, and all i get is raw html data echo'ed out.

After installation, i have my user in the members table, listed as admin.
But the admin table is empty. I tried to add the data in there myself, but i am not sure how it should be enterd or what values i would need to put in there for my user to be listed as super admin.

If i could get some help here it would be very appreciate!

**Comment by Xirez** [comment]
Alright, thank you for answearing!
Exciting times ahead! I will wait around for version 3.1 and try that version out instead. 
Thank you again for this beautiful script man!

**Comment by therecluse26** [comment]
No problem! I'm just happy people are getting something out of it :)

I'll also try to provide some more actual API documentation shortly after the next point release, so keep an eye out for that as well

**Comment by Nathan911765** [comment]
Absoloutely love your work on this ! it is easy enough to create php forms for a basic login stuff but this makes things 100% easier and with extra features ! any ideas on when version 3.1 will be out as I also have the issue of just raw html as I see many of the files currently do not have bootstrap included in them. Once v3.1 is released I will be installing this on my bootstrap template I use ready for my next site :)

**Comment by therecluse26** [comment]
Thanks man! It shouldn't be more than a week or two before it's out. I'm tweaking a few things (and I of course decided last night to refactor the entire thing to fit more in line with PSR-4 standards, so that'll add some extra time for testing and all that) right now and making sure that the role/permission functions work well together at this point, but after that, I'll release it. Some new documentation will be needed at that point as well. Not too much longer though!

**Comment by Nathan911765** [comment]
Sounds awesome ! I couldn't get the 3.0 to work properly bootstrap wasn't linking properly I will await the v3.1 :) it will be used as my backed login system for a administration panel for a new project I am building thanks for the awesome work keep it up ! I have yet to master web dev stuff mainly php and html !

**Comment by therecluse26** [comment]
Nice! What are you building with it? I always like to hear about how my library is being used :)

(this update should make development easier too as I've included some more user-friendly methods of validating permissions and so forth)

**Comment by therecluse26** [comment]
Just released version 3.1! Give it a go and let me know if you have any issues.

Btw, there's a migration tool in the `/install` directory for migrating the database from legacy versions to the new version. You'll want to install the app as new and then run the migration tool to pull the database over.

**Comment by therecluse26** [comment]
@Nathan911765 I released version 3.1, just fyi :) Give it a shot and let me know what you think!

**Comment by therecluse26** [comment]
There were quite a few bugs uncovered by you guys, which I've patched so if you haven't already, you might want to do another `git pull` to bring those fixes in
