### ISSUE TITLE
User deletion

### ISSUE THREAD

**Issue by hbrekke** [therecluse26/PHP-Login#185]
I can't seem to find any users. I have two users now (super admin and another I just made). And as a super admin I cant find other user and or delete them from this menu. Have I done something wrong?
<img width="1668" alt="skjermbilde 2018-05-22 kl 10 25 39" src="https://user-images.githubusercontent.com/39516106/40350580-8303b9be-5daa-11e8-9987-ac2f2b650c9d.png">

**Comment by luisbatista** [comment]
Hi,

The "Verify/Delete Users" option only show pending users from verification, not list all registered users.
You need to build an option to list users.

Regards,
LB

**Comment by hbrekke** [comment]
My bad :P
Thankes!

**Comment by therecluse26** [comment]
@hbrekke  Don't worry, I have more user management features incoming in version 3.1 that address this exact problem, also the ability to ban for a certain period of time :)
