### ISSUE TITLE
how to use the same database as PHP-Login

### ISSUE THREAD

**Issue by hbrekke** [therecluse26/PHP-Login#186]
I've wanted to use my own system along with PHP-Login, and do my own code inside the PHP-Login code. I see that in the database the users username etc. is encrypted. Is there a way to get the key, or run sql code to the database?

**Comment by therecluse26** [comment]
There's no encryption built into any of the database methods. I leave that up to each developer to handle on their own. The only thing that is hashed are passwords. You shouldn't have any trouble migrating the database with mysql

**Comment by hbrekke** [comment]
What about adminID and user ID?

**Comment by therecluse26** [comment]
No fields in the database are encrypted except for hashed passwords
