### ISSUE TITLE
Delete users

### ISSUE THREAD

**Issue by Munger** [therecluse26/PHP-Login#188]
Is it possible to delete registered user accounts?

**Comment by therecluse26** [comment]
That's coming with the next release in a few days! As of now, you'll have
to do it at the database level.

**Comment by therecluse26** [comment]
Just released version 3.1 which includes this feature! Give it a go and let me know if you have any issues.

Btw, there's a migration tool in the `/install` directory for migrating the database from legacy versions to the new version. You'll want to install the app as new and then run the migration tool to pull the database over.
