### ISSUE TITLE
PHP-Login/vendor/autoload.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by wbitholedotbe** [therecluse26/PHP-Login#192]
1. Automatic installation went well.
2. Then I get this:

Warning: require(/data/sites/web/mywebsite/www/PHP-Login/vendor/autoload.php): failed to open stream: No such file or directory in /data/sites/web/mywebsite/www/PHP-Login/login/misc/pagehead.php on line 8

There is no vendor folder or a autoload.php file

**Comment by therecluse26** [comment]
It looks like composer didn't run properly. If you open up a terminal to the root directory of PHP-Login, you should be able to run `composer install` to pull in all the required dependencies, and everything should work for you :)
