### ISSUE TITLE
Composer errors

### ISSUE THREAD

**Issue by nicktones** [therecluse26/PHP-Login#196]
Any advice on solving the composer install errors below?

Thanks in advance!

<img width="2560" alt="screen shot 2018-06-12 at 19 48 51" src="https://user-images.githubusercontent.com/2812641/41310573-c65731b6-6e79-11e8-929e-36cf44c6002d.png">

**Comment by therecluse26** [comment]
Hey Nick, try doing a git pull first and pulling in some changes I made to
the composer config file and run `composer install --no-dev` to ignore the
dev dependencies that are causing this issue. Unfortunately, there's no way
currently in composer's config to have it automatically ignore these
development dependencies that you don't necessarily need (like unit testing
and things like that), so you'll have to pass that `--no-dev` flag
explicitly

**Comment by nicktones** [comment]
Awesome - will give that a try and get back to you

**Comment by nicktones** [comment]
On testing now - new composer.json file has a extra unneeded comma on line 24.

**Comment by nicktones** [comment]
Still getting the errors below, with new composer.json and --no-dev
<img width="2560" alt="screen shot 2018-06-13 at 15 59 03" src="https://user-images.githubusercontent.com/2812641/41359612-c8c67b1a-6f22-11e8-981d-0a3913b43d70.png">

**Comment by therecluse26** [comment]
Ok, run one more git pull and try again. Sorry about that!
