### ISSUE TITLE
Fatal Error "Edit Profile" Admin

### ISSUE THREAD

**Issue by Miheix** [therecluse26/PHP-Login#198]
Fatal error: Uncaught TypeError: Return value of PHPLogin\ProfileData::pullAllUserInfo() must be of the type array, boolean returned in C:\xampp\htdocs\nameapp\login\class\profiledata.php:68 Stack trace: #0 C:\xampp\htdocs\nameapp\user\profileedit.php(6): PHPLogin\ProfileData::pullAllUserInfo('12343736875b214...') #1 {main} thrown in C:\xampp\htdocs\nameapp\login\class\profiledata.php on line 68

**Comment by Miheix** [comment]
Right after making the first login as administrator

**Comment by Miheix** [comment]
PHP Version 7.2.5

I've already tried it in two different places !

![image](https://user-images.githubusercontent.com/40177548/41380412-21ff660a-6f65-11e8-9ac6-8a3d4f61d858.png)

I do not know if I'm doing something wrong

**Comment by therecluse26** [comment]
Okay, I believe I got this sorted out. Try running a `git pull` and reload the page and you should be golden (fingers crossed)

**Comment by Miheix** [comment]
Okay, it works. Another error is when I try to register the clients.
![imagen](https://user-images.githubusercontent.com/40177548/41400934-bc6e8384-6fbe-11e8-841b-9e05d0c85764.png)

**Comment by therecluse26** [comment]
I'm not sure how I missed that... got that taken care of as well, so go ahead and do another pull. Thanks for pointing these out! This helps a lot

**Comment by therecluse26** [comment]
@Miheix I found and scrubbed out a few more similar return type bugs, so if you wanna do another git pull, it should all be in order now.
