### ISSUE TITLE
chat room

### ISSUE THREAD

**Issue by Heraclion** [therecluse26/PHP-Login#203]
Can you implement also chat rooms with chatbot  that saying welcome user to chatroom?

**Comment by byruddy** [comment]
this isn't issue dude, more other issue this project but i love ux installation

**Comment by therecluse26** [comment]
Sorry, that would be outside of the scope of what this was designed for. If you found a chatbot plugin to add, however, you could easily do that in the page code and use the available helper methods to determine user login state as well as role.
