### ISSUE TITLE
Nav Bar CSS 

### ISSUE THREAD

**Issue by atharvaunde59** [therecluse26/PHP-Login#217]
Hello,
Am trying to add material design touch to this so can someone help me to find CSS file for the navigation bar so that background of same can be changed !

**Comment by mattish91** [comment]
If you are using any web browser, you can right click the element of what you want to change, and click "inspect element" and that will show you the source code as well as the css for that element, also you will se what file it is and what line number the specific code element you are watching. 

(You can update the css code live in your browser to see if your code is alright, and when it's done you could simply copy the new code and just paste it in that element in the specified file on the right row.)

Hope this helps.

**Comment by atharvaunde59** [comment]
/vendor/components/css/bootstrap is having ,css and .css.map files am i supposed to edit all css files and .map files ? and also minified css files ?

**Comment by atharvaunde59** [comment]
CAN BE CLOSED!!
Issue Fixed!!

**Comment by mattish91** [comment]
This is only located in the file: /vendor/components/bootstrap/css/bootstrap.min.css edit 

Line: 2018 .navbar-fluid 
Edit like following: 

padding-right: 15px;
padding-left: 15px;
margin-right: -1px;
margin-left: -1px;
background-color: #333;
margin-top: -1px;

This should make it 100% width no 1px spacings on either side nor on top, also the background color would be #333 (grey scale 3).

**Comment by atharvaunde59** [comment]
I used following in nav.php file 
<nav class="navbar navbar-default" style="background-color:#179587">

**Comment by atharvaunde59** [comment]
`<nav class="navbar navbar-default" style="background-color:#179587">` in nav.php saved my day

**Comment by mattish91** [comment]
Not the right way to do it but if it works for you then I suppose it's all right. As a web developer I encourage to use cascading styles only where it's supposed to be, in the CSS files only, especially if a customer is involved, and that customer would replace me with someone else or if I got teammates editing these files in after hand, they would be totally pissed with me and ask the customer what dick head hard coded the styles in the php files xD and then the customer would probably tell him or her and that would just be bad PR. IF you can do it right, do it right, unless it's for your self, in that case it doesn't matter xD 

I always do it right the first time any ways incase I would have to release the code public some where or if I would in my turn hire someone to ease their burden from crappy code. Then they might get so pissed that they leave for just that reson. If it's an easy fix the first time around, it won't be the second time if the code is unknown to the designer.
