### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by Glen-Dango** [therecluse26/PHP-Login#226]
I am sure its awesome code but any demo so i can see what it actually does? thx

**Comment by qublibjohnny** [comment]
+1

**Comment by mattish91** [comment]
Basically what it does is giving you an simple way to login, no content management except for some profile details, name, lastname and such. the content is all up to you, you get some files that is permission based that is checking against a database if you admin or not and from that information checks if you are allowed access to see the page content or not. and that's it. 

No demo needed,  it's straight forward to try it on your own machine. 
If you're running Windows, install Wamp and try the code there. 
If you're running Mac,  install Mamp and try the code there. 
If you're running Linux, Install Lamp and try the code there.

**Comment by Glen-Dango** [comment]
great thanks for the explain. i will check your docs to see how to get it
working with Wamp.
