### ISSUE TITLE
Keep user logged in feature

### ISSUE THREAD

**Issue by heyrm** [therecluse26/PHP-Login#23]
Hey Fethica,

Are there any plans to add a "keep me logged in" feature?

I think this framework would be perfect if this was added.

**Comment by therecluse26** [comment]
Could you add that as a feature request in issues? I can add that in the
near future once some things settle down for me :)

On Wed, Jul 13, 2016 at 12:19 PM, Romero Mckay <notifications@github.com>
wrote:

> Hey Fethica,
>
> Are there any plans to add a "keep me logged in" feature?
>
> I think this framework would be perfect if this was added.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fethica/PHP-Login/issues/23>, or mute the thread
> <https://github.com/notifications/unsubscribe/AH24AsJDR-mQcT3-yfbWq84-Fjgrs8HUks5qVRAWgaJpZM4JLmK9>
> .
>



-- 
- bradley david

**Comment by upggr** [comment]
Is there a setting currently to keep user logged in for a set time? for example a day?
Looks like this is only for inactive logins?: 
//Maximum Login Attempts
$max_attempts = 5;
//Timeout (in seconds) after max attempts are reached
$login_timeout = 400;

**Comment by heyrm** [comment]
@therecluse26 Hey I don't believe I can change it to a feature request. Only the admin/collaborators can add the correct labels.

**Comment by heyrm** [comment]
@upggr You could just do this in JS its pretty simple

**Comment by therecluse26** [comment]
Yeah, I'll knock it out when things settle down a bit, like I said. I'm getting married in less than 2 weeks and work is very busy so life's pretty crazy right now. Very sorry about the delay!

**Comment by heyrm** [comment]
@therecluse26 Congrats! Take your time mate :)

**Comment by heyrm** [comment]
Hey, its been a while are any updates coming?

**Comment by therecluse26** [comment]
Hey, sorry about the delay. I'm making a lot of progress, but also have been running into numerous potholes along the way, as always is the case. That being said, it's getting closer and closer... thank you for your patience! :)
