### ISSUE TITLE
Forgot password feature?

### ISSUE THREAD

**Issue by rabih9780** [therecluse26/PHP-Login#25]
Are you planning on adding forgot password feature?

Thank you :)

**Comment by therecluse26** [comment]
Yep! It's in my near future plans, but I'm getting married next week, so I'm pretty busy for the rest of the month. I plan on getting to it next month though :)

**Comment by rabih9780** [comment]
Alright, thanks getting back to me quickly! Congrats on your marriage

**Comment by barryhatfield** [comment]
+1 for forgot password

**Comment by jorisssss** [comment]
+1

**Comment by cenkdominic** [comment]
+1

**Comment by VA7NFH** [comment]
I just forked and I am planning to add this feature soon.

**Comment by therecluse26** [comment]
Give me like 10 more minutes to push my latest commit before you do that

**Comment by therecluse26** [comment]
Okay, here's the current version of the project in development:

https://github.com/fethica/PHP-Login/tree/dev

Still tweaking things up, so there will be incoming changes periodically
before I finalize the release, but this has forgot password functionality,
cookies, additional security measures, a navbar with user controls
integrated, an admin panel, user profile controls and more. If you have any
tweaks you want to make, feel free!

**Comment by VA7NFH** [comment]
I've Got a pull request (#62) with a fully working password reset feature.

**Comment by VA7NFH** [comment]
Great well I will close my pull request then.
