### ISSUE TITLE
If you have enabled "moderator verification" the moderator's email is used to create a new account and likely fails

### ISSUE THREAD

**Issue by falconapps** [therecluse26/PHP-Login#28]
In the file `login/createuser.php` there is code:

```
    //Enables moderator verification (overrides user self-verification emails)
if (isset($admin_email)) {
    $newemail = $admin_email;
} else {
    $newemail = $_POST['email'];
}
```

Then later (line 43) we add:
`$response = $a->createUser($newuser, $newid, $newemail, $newpw);
`

In the case of moderator verification, we are adding the moderator's email, not the user's, and this will fail in short order.  We should use for line 43:

```
-        $response = $a->createUser($newuser, $newid, $newemail, $newpw);
+        $response = $a->createUser($newuser, $newid, $_POST['email'], $newpw);
```

**Comment by Sir-Lagsalot** [comment]
I was having trouble with this. This solution worked.

**Comment by Gunsmithy** [comment]
I was also having trouble. Whenever I created a second user it would say the username or email is already taken. Your solution fixed it thank you!

**Comment by Cykhet** [comment]
I created another issue on this matter and provided another solution which also addresses the end user not being properly notified upon registration that admin verification is enabled. #33 for the code edits.
