### ISSUE TITLE
$admin_email set, verification message doesn't notify user that admin approval is enabled.

### ISSUE THREAD

**Issue by Cykhet** [therecluse26/PHP-Login#33]
To replicate this issue, register an account then set $admin_email to reflect the email address of the previously registered user within config.php. Once this has been done, attempt to register a new user account. Doing so will result in the following error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'example@domain.com' for key 'email_UNIQUE'

This is due to $newemail being populated with $admin_email which is then subsequently used to create the user account. If the admin email has already been used for a prior registration, a duplicate entry violation will occur.

Additionally, when $admin_email is populated and a new user registers, the user isn't notified that admin approval is enabled and will require manual input. The desired result is that the end user will receive a message notifying them of such requirement.

**Comment by Cykhet** [comment]
This can be temporarily remedied by the following code edits and additions. Note, this is subject to change by the author.

Within config.php, line:37 add the following:
`$requiresadminapproval = 'Thank you for signing up! Before you can login, your account needs to be activated by an administrator.';`

Within createuser.php, delete the following lines:

```
if (isset($admin_email)) {

    $newemail = $admin_email;

} else {

    $newemail = $_POST['email'];
}
```

line:8 insert the following:

`$newemail = $_POST['email'];`

line:12 add the following 2 lines:

```
$verifyemail = (isset($admin_email)) ? $admin_email : $newemail;
$successmsg = (isset($admin_email)) ? $requiresadminapproval : $signupthanks;
```

line:41 change the following:

`echo '<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'. $signupthanks .'</div><div id="returnVal" style="display:none;">true</div>';`

To:

`echo '<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'. $successmsg .'</div><div id="returnVal" style="display:none;">true</div>';`

line:45 change the following:

`$m->sendMail($newemail, $newuser, $newid, 'Verify');`

To:

`$m->sendMail($verifyemail, $newuser, $newid, 'Verify');`

**Comment by radiofreq10** [comment]
Thank you! This worked for me!
