### ISSUE TITLE
user session - enhancement 

### ISSUE THREAD

**Issue by kerrial** [therecluse26/PHP-Login#38]
Thank you very much for sharing such a great resource. 
Maybe it would be an idea to add how to use the current session into the information. 
For example, how to fetch the current users information from the database.

**Comment by AgustinQuetto** [comment]
Hi Kerrial! Want to create session variables? They can do this by declaring them to create the session just by $ _SESSION

```
//Success! Register $myusername, $mypassword and return "true"
                $success = 'true';
                    session_start();
                    $_SESSION['username'] = $myusername;
                    $_SESSION['example'] = $example or $result['myrow'] or int or string...;
```

$_SESSION is a global variable. You can use it directly. For example:

```
if ($_SESSION['username'] == "Ash") {
   echo "Hello my little friend";
}
else {
    echo "Get out."
}
```


For fetch the current user information from the database you can create a $_SESSION variables or a query with the current username into the $_SESSION value.

**Comment by kerrial** [comment]
Thanks for the quick reply. Yes, that's what I figured. However, I couldn't fetch the current user information from the database using $_SESSION variables. Would you be so kind to show and example of how to do this?   

I can access the current session like so and echo out the username: 

`if(isset($_SESSION['username'])){
echo "{$_SESSION['username']}";
}
?> `

However the other columns will not display using this method.

**Comment by AgustinQuetto** [comment]
```
if(isset($_SESSION['username'])){
  echo $_SESSION['username'];
}
```

or

```
if(isset($_SESSION['username'])){
  echo "Hi ".$_SESSION['username']."! Welcome.";
}
```

**Comment by AgustinQuetto** [comment]
or

```
$myuser = $_SESSION['username'];

if(isset($myuser)){
  echo "Hi $myuser! Welcome.";
}
```

You can put variables $example directly into your string. You can't put variables with [''] directly without "". .""; into your string. Sorry for my bad english.

**Comment by AgustinQuetto** [comment]
You can set a new variable when the session has stared.

//Success! Register $myusername, $mypassword and return "true"
                $success = 'true';
                    session_start();
                    $_SESSION['username'] = $myusername;
                    $_SESSION['email'] = $result[email'];

Now you can echo.

$myuser = $_SESSION['username'];
$myemail = $_SESSION['email'];

if(isset($myuser)){
  echo "Hi $myuser! Welcome.";
  echo "Your email is: $myemail";
}

**Comment by kerrial** [comment]
Wow, thanks so much for all the information! Your english is good, just so you know I think there is a syntax error in this this line of code: 

`  $_SESSION['email'] = $result[email'];`

should be:
`  $_SESSION['email'] = $result['email'];`

also all the echoes are blank, displaying nothing.

**Comment by AgustinQuetto** [comment]
Yes, there is a syntax error when I wrote. Fixed. Sorry! You could solve the problem?

**Comment by kerrial** [comment]
Thank you. Unfortunately, not. If I use the last example, nothing is displayed.

**Comment by kerrial** [comment]
I have managed to get it to display "Hi User Name! Welcome.Your email is:               "
but it had to remove this for some reason:

`//Success! Register $myusername, $mypassword and return "true"
                $success = 'true';
                    session_start();
                    $_SESSION['username'] = $myusername;
                    $_SESSION['email'] = $result['email'];`
