### ISSUE TITLE
Both passwords on registration are usable

### ISSUE THREAD

**Issue by flam3srock** [therecluse26/PHP-Login#48]
If you create a user and both passwords are different, in my case off by one & character, you can login with either password. It seems that the hash that is created for whatever reason corresponds to both.

**Comment by therecluse26** [comment]
Hi, I'm unable to replicate the problem, can you tell me what steps you
took to cause this error?

On Mon, Nov 28, 2016 at 9:43 PM, flam3srock <notifications@github.com>
wrote:

> If you create a user and both passwords are different, in my case off by
> one & character, you can login with either password. It seems that the hash
> that is created for whatever reason corresponds to both.
>
>



-- 
- bradley david

**Comment by flam3srock** [comment]
It seems that I failed to create the loginattempts table. I'm not sure if thats the reason why, but it works perfectly and I can't recreate the issue.

**Comment by therecluse26** [comment]
Well that's good news... I'm guessing you got the loginattempts table up
and running?

**Comment by kernelsp** [comment]
Maybe a little off-topic but might come in handy and save a lot of time. Ppl with this issue should be aware that if your password_hash can't tell the difference between uppercase and lowercase passwords (eg.: 'Test' and 'test') it is not password_hash's fault. You should check your collation on your database. If it ends with "*_ci", notice that the "i" stands for case-insensitive and if it ends with "*_cs", the "s" is for case-sensitive.
