### ISSUE TITLE
Syntax error when signup is submited (createuser.php)

### ISSUE THREAD

**Issue by purgeru** [therecluse26/PHP-Login#56]
When I try to signup it gives me an error (shown below) and I can not enter new member in database.

![issue1](https://cloud.githubusercontent.com/assets/3590917/21636562/749bce8a-d263-11e6-8637-a4d2f8ce61c7.JPG)

**Comment by kernelsp** [comment]
Hi,

Have you edited createuser.php? Could you post the code as it is now? Most likely you have inserted a character on that line by accident.

---- On Wed, 04 Jan 2017 05:53:53 -0300 notifications@github.com wrote ----

When I try to signup it gives me an error (shown below) and I can not enter new member in database.
