### ISSUE TITLE
Issues with the Dev branch - permissions.

### ISSUE THREAD

**Issue by TheJakeBrown** [therecluse26/PHP-Login#68]
Hi ^ ^

Sorry for my english first off.
Heres the error in the install folder:
PHP-Login is not writable! Current permissions: 0755
Please run the following terminal command and refresh the page: 
And then gives me commands to run.

I have run these commands and tried everything, however, none work. Please help me fix this! The project is great and by the looks of it, really active.

Regards,

Jake

**Comment by therecluse26** [comment]
Are any errors showing up? I was having issues with this yesterday (and
they're still being ironed out). Have you made your server daemon user
(often "www-data" or something similar) the owner of the folder? If not,
try running:

 sudo chown -R [server-user] [path-to-php-login]

**Comment by TheJakeBrown** [comment]
Yes i did that - it asked me too. I tried that and rebooted my server as-well as everything else on server forums. I made it the owner yes.

**Comment by therecluse26** [comment]
I think it has to do with the PHP-Login/install/tmp directory. Try setting
that to 777

**Comment by TheJakeBrown** [comment]
Its still not working :( I want it to work as it looks like the best one on Github

**Comment by therecluse26** [comment]
No worries! We'll get you up and running... any errors in your php error
log?

Try removing the directory and cloning it again from git

**Comment by TheJakeBrown** [comment]
No errors in PHP log.
Removed git clone, updated to PHP 7, still not working. 

Much thanks for help!

**Comment by therecluse26** [comment]
Sorry to hear that... if you feel comfortable, I would be happy to ssh into
your server and see if I can get it up and running for you. It would help
me figure out what the root of the problem is as well because others are
having similar issues, so it's clearly something I need to iron out in the
code. If you do feel comfortable with that, you can email me at
braddmagyar@gmail.com

If not, I totally understand! Just want to help :)

**Comment by TheJakeBrown** [comment]
i could do that, of course.
i have lots of important files on it though so i have to make a test server.
however, it would be nice to try and get the issue solved via just messages. now the error is still there but on submit it goes to this The page isn’t working
currently unable to handle this request.
HTTP ERROR 500
i then tried to make the file permissions 777 it got rid of red error, but on submit the same http error occurred.

thank-you

**Comment by therecluse26** [comment]
@TheJakeBrown , totally understand. What do your error logs show? 

If you have logging turned off, try adding this to the top of your PHP-Login/install/install.php (and index.php if there are issues there)

<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

**Comment by TheJakeBrown** [comment]
ahh i make you test server now, please tell me how you did it though so i can apply to big server.
but please read last thread so you can see the new error thing /\
thankyou!

**Comment by therecluse26** [comment]
@TheJakeBrown it's most likely an issue with the installer code, it needs fine-tuning. It's hard to tell what is causing the error if I don't have any error details, so I'll try to figure it out for you

**Comment by TheJakeBrown** [comment]
@therecluse26 so here's the info:
note: im on centos7 with sentora panel installed. Once again, this is a test server i made just for you - if you could tell me how you fixed it so i can do on my big server i will be a very happy man :)
IP: 45.63.4.168
Password: n2@D6+?yeZ%VB-KF
domain i put it on: oxro.ml
how to get to directory? cd /var/sentora/hostdata/zadmin/public_html/oxro_ml/PHP-Login
database information:
host: localhost
username: oxro
password: pe6egemu3
dbname:  zadmin_login

thanks so much!

**Comment by therecluse26** [comment]
Cool, what's the sentora login info?

**Comment by TheJakeBrown** [comment]
Login to Sentora at http://my.eddiej.pw
 Sentora Username  : zadmin
 Sentora Password  : WmikPprxIF3lnhJM

**Comment by TheJakeBrown** [comment]
Login to Sentora at http://my.oxro.ml
 Sentora Username  : zadmin
 Sentora Password  : WmikPprxIF3lnhJM

**Comment by eddiethejibson** [comment]
@TheJakeBrown Haha, no problem. I only use that server to test out things I've been working on, so it's fine. I hope your issue gets sorted soon.

**Comment by therecluse26** [comment]
@TheJakeBrown poked around a bit more, and it's just far too restrictive for me to do anything with. If you need more help, I'll need an SSH account that allows me to sudo and change file/directory ownership and permissions

**Comment by TheJakeBrown** [comment]
@therecluse26 hello. any update? thanks again.

**Comment by TheJakeBrown** [comment]
@therecluse26 if you're busy, I could pay you to fix this? It looks like good platform and I really want it to work.

Thankyou

**Comment by therecluse26** [comment]
Hey @TheJakeBrown , sorry yeah I have been pretty busy... if you could send me an email at braddmagyar@gmail.com, we can talk more on there

**Comment by therecluse26** [comment]
Okay, I think I got it working, if you wanna try logging in with the following credentials:

http://oxro.ml/PHP-Login
user: thejakebrown
pw: Asdfasdf

I didn't know your email, so I just put mine in temporarily, so you'll want to go to your user menu in the top right corner and change it under Account Settings. You'll definitely want to change your password there as well. Then make sure you go under that same menu and fill out the appropriate settings in the "Edit Site Config" section. Setting up your SMTP mailer settings is of primary importance. 

To explain, there were a few issues I was running into. First of all, that Sentora system was really restrictive, so I had to bypass it and do most of what I wanted through SSH. I had to use a database user (root, in this case) that had appropriate permissions (you'll want to change this later in the /login/dbconf.php file), and I also had to edit your php.ini file to give php enough memory to allow composer (located at /install/composer.phar) to install the necessary dependencies. I've since switched that back. 

The installer definitely still needs work, but it looks like we got it up and running! I don't require payment, but I wouldn't turn a donation if you're offering ;)

**Comment by TheJakeBrown** [comment]
Thank you. I will test and see if this works on my big server. If it does, Ill donate.

**Comment by TheJakeBrown** [comment]
@therecluse26 Ok, so on me trying to fix it on my big server, I encountered only one problem, where is my php.ini file? And what do I replace it with? I couldn't find it in the test server I created for you either, as I was just going to copy and paste it but i couldn't find it... I'm happy to donate if this is fixed

**Comment by therecluse26** [comment]
Run this in the command line to find the loaded configuration file: php
--ini

and then increase the memory_limit value and restart your apache server and
try again. Once it's over, try resetting that memory_limit value to what it
was previously and restart apache again

**Comment by TheJakeBrown** [comment]
Hi,

Just tried doing it through root SQL, normal (With all permissions) and adjusting the PHP.ini file (then even switching it back) but the error (Not the message), "The page is not working" still occurs?

If you could tell me step by step what you did, I'm happy to donate 50 euros as I really need it done.

Thanks.

**Comment by therecluse26** [comment]
Sure, can you shoot me the URL and I'll see if I can figure out what the
cause is?

**Comment by TheJakeBrown** [comment]
Here's the domain: http://oxro.cf/PHP-Login/ 
As I said, I tried with root, and adjusting the php.ini file but it will still say "The Page Is Not Working"?

Could you tell me the exact steps?

Thanks

**Comment by therecluse26** [comment]
Can you throw this up on your server as well and hook it up to your error
log files? I can't do anything without being able to see logs
http://pimpmylog.com/

**Comment by TheJakeBrown** [comment]
I just tried installing PimpMyLog and to install, I need to change important configuration of some of my server like the PHP file. Obviously I'd change if I needed for PHP-Login, but I don't think it's needed. Any other way of displaying the log?

**Comment by TheJakeBrown** [comment]
@therecluse26 I mean, the server configuration are almost identical so if you could tell me what you did on the other server fully, I could try that?
