### ISSUE TITLE
Can't use function return value in write context

### ISSUE THREAD

**Issue by binaryflow** [therecluse26/PHP-Login#69]
Hello! I'm trying to set up PHP-Login (master branch) on a brand new project. When trying to set up the first user the page sits forever and the following event is written to the error log file:

PHP Fatal error:  Can't use function return value in write context in /path/to/login/createuser.php on line 37, referer: https://sanitized.url.com/login/signup.php.

We are running CentOS 7 with PHP 5.4 and latest mariadb. I have set up the database tables per the readme file. I realized I was missing the PHPMailer files from your source code so I pulled down the files from the linked repo and placed them in the same place.

Is there some additional setup step I am missing? Is PHP 5.4 an issue? Is there any way to avoid using PHPMailer and use the mail() function in PHP? Thanks for your help with this!

**Comment by therecluse26** [comment]
It definitely could be a 5.4 issue... the password_hash function is as the
core of the project which wasn't implemented until 5.5, so we recommend
5.6+ (7 is preferred)

**Comment by binaryflow** [comment]
I don’t have any servers running higher than 5.4. This is going to take some planning. Thanks for your help with this!

**Comment by therecluse26** [comment]
Yeah, this library won't work without the password_hash function and I
imagine there may be other features that break as well. I would suggest an
upgrade to PHP version 7, you'll dramatically increase your performance (up
to 3x the speed in many instances!) and compatibility with new libraries
