### ISSUE TITLE
Help with installation.

### ISSUE THREAD

**Issue by april-ren** [therecluse26/PHP-Login#72]
Hi,

So I'm basically a complete beginner at coding. I stumbled across this in looking for a decent, secure, active PHP Login system. I was told by an acquaintance to clone your dev branch to my server (Centos7 with PHP and Apache installed with a panel which is free and popular for my platform). I created a SQL account, granted it all the permissions and went to the setup page. I entered all the information correctly, and on submission, the page just displayed “The page is not working” I tried multiple things, but nothing worked. 
I’m more than happy to give you the SSH for the server so you can see what’s wrong, but if at-all possible, I’d like to know exactly how to fix it. As I’m sure you know, that’s the only way for me to learn and think it’s important for more females to get into development ;)

Thankyou!

April

**Comment by magarrajan** [comment]
Create database "login" and create tables "members" and "loginAttempts".

**Comment by april-ren** [comment]
@magarrajan haha what? I don't even need to create the tables as I assume the installation script does that itself. I'm talking about the dev branch. And, if you read my issue carefully, that's not the issue at all.

Thanks anyway.

**Comment by JanPetterMG** [comment]
Is it Chrome (or some other browser) saying _"The page is not working"_?

It's probably an "php fatal error"
Put this in the top of your page, do you get any error messages now?
````
error_reporting(E_ALL);
ini_set('display_errors', 1);
````

**Comment by magarrajan** [comment]
@april-ren please send screenshort of issue.
![capture](https://cloud.githubusercontent.com/assets/18038852/23388444/3e4e88a4-fd88-11e6-9b44-244de5712d9a.JPG)

**Comment by april-ren** [comment]
@JanPetterMG I added it! Seems to have done something... No longer says "Page is not working" but instead says this: Fatal error: Call to undefined function password_hash() in install.php on line 19

Any suggestions?

@magarrajan The screenshot isn't needed, what I can see is above thanks to the error reporting suggestion.

Thank-you for your help!

**Comment by VA7NFH** [comment]
@april-ren What is your php version?
This requires 5.6+ and 7.0 is highly recommended.

**Comment by april-ren** [comment]
On 5.6 at the moment. Thanks.
