### ISSUE TITLE
Not receive email for verification

### ISSUE THREAD

**Issue by ShafiqqAziz** [therecluse26/PHP-Login#75]
Manage to sign up but cannot log in due to not receiving the email to verified. Refreshed like hundred times, wait for at least ten minutes, but nothing showed up. What's happened? Any help?

**Comment by coggie** [comment]
Hi anybody after a full working PHP and MYSQL Members and new users login
and sign up form?  I have a full security tested login with google
recapture.  I am able to offer my services to anybody for a very low price
and i will if you need me to set the accounts sign up for you.  I would not
use this New PHP LoginMaster from github as i dont think it hasd been
tested fully and as fare as i no it still has the problems login and
sending the email to varify the account.  Anybody want a full working sign
up can contact me at ccogdell54@gmail.com

**Comment by therecluse26** [comment]
@ShafiqqAziz who is your email provider? If it's something like gmail, you may have to grant your application access to login to and use your account via smtp

**Comment by ShafiqqAziz** [comment]
i used gmail, edit the config.php to fit with gmail smtp but nothing work

**Comment by GillesC** [comment]
@therecluse26 I'm also using gmail. Could you provide a link to a tutorial on how we can grant our application access to our gmail account?

**Comment by therecluse26** [comment]
This should do the trick
https://support.google.com/accounts/answer/6010255?hl=en


On Fri, Mar 31, 2017 at 10:30 AM, Gilles Callebaut <notifications@github.com

**Comment by GillesC** [comment]
Thank you, but I've already turned my Access for less secure apps on.
Thus, that was not the issue...

**Comment by lalikarl** [comment]
Hi,

Is there a way to avoid email confirmation?

**Comment by therecluse26** [comment]
Yes, are you using the dev branch version? There's a setting in there to
force admin verification.

**Comment by eirikss** [comment]
is there a way to turn of BOTH email confimation and admin verification?

**Comment by therecluse26** [comment]
Yes, in the dev version, this is supported. If you allow users to confirm
themselves through email, they will still show up in your admin
confirmation panel.

**Comment by eirikss** [comment]
The SQL part of the register works fine, but when registering, no email is being sent. I have put my details into  "Config.php" and theese details my Website/Domain-provider have comfirmed is correct. Do you have any suggestions to where i should start to check for errors/things i have done bad?
