### ISSUE TITLE
[Request] Variable to change where the page will load after signing in

### ISSUE THREAD

**Issue by Shagon94** [therecluse26/PHP-Login#77]
Example, after signing in, instead of going to index.php it changes automatically to $directoryname.php

I tried editing login.js and login.coffee but couldn't make it work.

**Comment by JanPetterMG** [comment]
Try main_login.php line 4, that works.
I would love to see an feature redirecting you back to the previous page you're visited when got redirected to the login form. That's a much better alternative than an static page.
BTW. I've tested using the server referrer variable, and it doesn't work out of the box...

**Comment by Looxoor** [comment]
@JanPetterMG It already (sort of) does. It just needs a little tweaking.

When I try to go to profileedit.php when I'm logged out, it gets redirected to $BASE_URL/index.php with a refurl attached, like so:

https://holwarehouse.ddns.net/php-login/index.php?refurl=http%3A%2F%2Fholwarehouse.ddns.net%2Fphp-login%2Fuser%2Fprofileedit.php

Just change the behavior to use login.php as redirect when logged out and in it check get just before the end of the script if authorized.

Right?

**Comment by JanPetterMG** [comment]
You're on the `dev` branch, right? I'm on `master`, as the install script never finishes, even on clean setup, no clue why...

Sounds like things are going in the right direction then, just some tweaking left

**Comment by Looxoor** [comment]
Yeah, that's right, I had to retry a couple of times before I got it right, I think I explicitly allowed all errors and warnings to debug the install. And some chmod tweaking of a couple of files/folders. More verbose installation and/or logging would be a nice addition in the future as well.
