### ISSUE TITLE
I cant do anything

### ISSUE THREAD

**Issue by 4Crea** [therecluse26/PHP-Login#84]
Hello, i need your help for your project on GitHub.

I have some issue, when i try to login or create new user its not working and doesnt give an error or anything.Only the circle is turning.Can you help me?

Screen shot : http://prntscr.com/eyw4ed
Website : http://212.237.11.168/login/main_login.php

Im using CentOS 6.7 , PHP 5.3.3 , MySQL 5.1.73

**Comment by therecluse26** [comment]
This project requires PHP 5.5 and above. I would recommend moving to PHP 7,
for the massive performance gains you get on top of that.

**Comment by coggie** [comment]
Hi all if you would like to get your website secured and are having
problems with the Login Master on github,  I can install on any platform
for you the best login system with no bugs and fully working.  I'm trying
to get myself out there so will work for cheap.  If you would like to speak
with me to find out more then you can message me at freetvnpt@gmail.com

**Comment by therecluse26** [comment]
This requires PHP version 5.5+

Version 5.4 will not work because the password_hash function that is
utilized in this script was introduced in version 5.5

http://php.net/manual/en/function.password-hash.php

**Comment by 4Crea** [comment]
@therecluse26 Thanks for everything but this time i cant do upgrade PHP 5.4 to 7 on CentOS 6.7

http://prntscr.com/ezbany

Its not connecting to fedoraproject.org

**Comment by 4Crea** [comment]
I fixed this issue and its working.Thanks for everything. @therecluse26  Have a nice day!

**Comment by therecluse26** [comment]
Great! Did you figure out how to upgrade?

**Comment by foen** [comment]
how did you fix this have same problem updated to 7.0 same problem stuck on loading values are inserted into he database I did check this.

**Comment by comconet** [comment]
I have the same problem.  But I have PHP version 5.6.25
