### ISSUE TITLE
What to do, if no PDO driver installed on server?

### ISSUE THREAD

**Issue by Stobal** [therecluse26/PHP-Login#85]
On my own test server it runs ok. I was wondering though, after installing it out there for production, I got errors. I set the dbconn to shoe the exceptions $e, which throws: 
Database connection error in class DbConn exception 'PDOException' with message 'could not find driver' in /web/cgi-bin/mydomain/login/includes/dbconn.php:19 Stack trace: #0 /web/cgi-bin/ottoauto/login/includes/dbconn.php(19): PDO->__construct('mysql:host=db.o...', 'mydatabase', 'mypassword') #1 /web/cgi-bin/mydomain/login/checklogin.php(17): DbConn->__construct() #2 {main} 
As far as I can judge, this means that the PHP on that server doesn't have the PDO driver installed. I tried to build a mysqli class instead, but it doesn't work either, because I'm not experienced enough to write it properly. 
Any help?

**Comment by therecluse26** [comment]
Do you not have access to the machine to install the PDO driver?

**Comment by Stobal** [comment]
No. It's a commercial provider, where I don't have rights to write or execute in the directories where php resides. The provider isn't interested to improve my domain without upgrading to a more expensive one. They do have PDO drivers but only for sqlite2 and sqlite, not for Mysql, although on the same srver I have from them a mysql database. Mysqli is there, php is version 5.2.3. 
Maybe I have to look for another older login routine that deals well with vanilla mysql?

**Comment by therecluse26** [comment]
Yeah, or switch providers. I would recommend running a login system without
some sort of database wrapper like PDO for flexibility, security and
sanitation purposes. You could maaaaybe try digging into some of the code
and converting the queries (they're relatively simple) to sqlite instead of
mysql, alternatively, but my first suggestion would be to go with a hosting
provider that gives you root access to your own VPS so you can do what you
want with it. Just my two cents.

**Comment by Stobal** [comment]
Hey, I checked again and I think my provider has after my inquiry opened up the directories for me. I now can at least red them with ftp. So, my next problem: even if I got the rights, I wouldn' know how to install the PDO driver for Mysql and what I would have to set in php configuration and where?

**Comment by therecluse26** [comment]
https://askubuntu.com/questions/824485/how-to-activate-php7-0-pdo-in-16-04-lts

**Comment by comconet** [comment]
Just as an insight, I have a host provider I queried about access to a virtual host with php, namely ...  As soon as I can test the wampserver positively with login.php on my localhost, I hope to move it all to a remote server for applications:  http://www.ipage.com/join/index.bml?bannerID=886&AffID=655332
