### ISSUE TITLE
How to change Login Success Page

### ISSUE THREAD

**Issue by imranitian** [therecluse26/PHP-Login#86]
Sorry, New to php. Where to make changes to redirect to a page index.php upon successful login.

**Comment by jontek2** [comment]
Edit index.php to:

`<?php require "login/loginheader.php"; ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your title</title>

</head>
<body>

YOUR CONTENT    
 
</body>
</html>
`

**Comment by snick512** [comment]
This was a bit of a pain for me, but I added a workaround .Using ?goto as a parameter to throw in the correct URL. Additionally, you can do what jontek2 suggested, or editing the login.php directly (below).

Reploace loginheader.php with:

```
<?php
//PUT THIS HEADER ON TOP OF EACH UNIQUE PAGE
session_start();
if (!isset($_SESSION['username'])) {
    
function url_origin( $s, $use_forwarded_host = false )
{
    $ssl      = ( ! empty( $s['HTTPS'] ) && $s['HTTPS'] == 'on' );
    $sp       = strtolower( $s['SERVER_PROTOCOL'] );
    $protocol = substr( $sp, 0, strpos( $sp, '/' ) ) . ( ( $ssl ) ? 's' : '' );
    $port     = $s['SERVER_PORT'];
    $port     = ( ( ! $ssl && $port=='80' ) || ( $ssl && $port=='443' ) ) ? '' : ':'.$port;
    $host     = ( $use_forwarded_host && isset( $s['HTTP_X_FORWARDED_HOST'] ) ) ? $s['HTTP_X_FORWARDED_HOST'] : ( isset( $s['HTTP_HOST'] ) ? $s['HTTP_HOST'] : null );
    $host     = isset( $host ) ? $host : $s['SERVER_NAME'] . $port;
    return $protocol . '://' . $host;
}

function full_url( $s, $use_forwarded_host = false )
{
    return url_origin( $s, $use_forwarded_host ) . $s['REQUEST_URI'];
}

$absolute_url = full_url( $_SERVER );
    
    header("location:login/main_login.php?goto=$absolute_url");
}

```

Then in main_login.php. Only replace the top portion:

```
<?php
session_start();
if (isset($_SESSION['username'])) {
    
$goto = $_GET["goto"];
    
    header("location:$goto"); // or the page you want to force the user after login location:https://your-url.tld
}
?>
```

Finally, you want logout.php to be:

```
<?php
    session_start();
    session_destroy();
    header("location:https://your-url.tld");
```

Maybe this feature will be added by default in the future, but this new-found workaround works for me. Maybe you'd want to sanitize or whitelist URLs.
