### ISSUE TITLE
Signup is turning forever

### ISSUE THREAD

**Issue by bjcd** [therecluse26/PHP-Login#92]
Hello all,

First I have to say that I'm very (very, very) new to github. I installed PHP-login and everything seems to work fine except that when I sign up, the icon at the bottom of the form keeps on turning and nothing happens. However, it seems like the user is created (visible in the database), but I need to manually "verify" the account from the db. No email is sent, no confirmation message is shown after validating the subscription.

My assumption is it is caused by the way I installed it. I downloaded it directly from the website and therefore I probably don't have PHP-Mailer installed.

THE thing is I have nooo idea how to do the first step:

**Clone the Repository (recursively to include PHP-Mailer submodule)
$ git clone --recursive https://github.com/fethica/PHP-Login.git**

Should I download a software or something? I'm running on Mac Os.

Many thanks for your help.

**Comment by bjcd** [comment]
I actually managed to have the PHPMailer added manually at the proper location (I just downloaded it from github and placed it in the appropriate folder). Now i have the confirmation message, but the email is not being sent. 

I use Gmail and I enabled access for less secured app.

Please help! :)

**Comment by GambitXii** [comment]
**"bottom of the form keeps on turning and nothing happens"** 
There is something wrong in code, It does not affect functionality of code if you turn off errors :)
In .htaccess remove **php_value display_errors 1**  and it will works like a charm :)

 **"i have the confirmation message, but the email is not being sent."** 
after you enabled access for less secured app. you need to wait some time, also check if pop3 is enabled in settings.  

I hope that this will help you.

**Comment by comconet** [comment]
I have the same problem.  But I'm using a Wampserver on my desktop to test everything locally, and I can't find an .htaccess that's not on my host remote server.

**Comment by streamcoindev** [comment]
how did you do this ?

**Comment by abdelouali** [comment]
Try it first on a real server. Everything works fine here. 

Best Regards
