### ISSUE TITLE
get "Username or email already exists" when entering the 2nd. person in DB

### ISSUE THREAD

**Issue by arneessa** [therecluse26/PHP-Login#94]
I have now tried 3 times: downloaded the exact clone from github. modified the necessary configuration files. and set up the database.
Then the first name w. email addr. is entered into the database without any problem.
However when entering the next name+email  I receive the dreaded message in the signup.php/createuser.php:  "Username or email already exists" 
I have now 3 times deleted all code and database.
Downloaded again, installed and modified and continuously get the message "Username or email already exists"Use PHP 5.6  and MariaDB.
Anyone have a suggestion for how to fix it?
Anyone have a suggestion for setting tracers to locate the problem code?
best regards
Arne;
arne@aem-e.com

**Comment by GithubberSD** [comment]
There is a bug in the code if you use an $admin_email. Are you using that?

When creating the member in the database the $admin_email is used as email, so the second member has also the $admin_email as email. 

To solve this problem you have to change one line of code in "login/createuser.php"

Change

$response = $a->createUser($newuser, $newid, $newemail, $newpw);

in

$response = $a->createUser($newuser, $newid, $_POST['email'], $newpw);

Now the email adress which is used in the signup form is always used for creating a new member.

**Comment by lukesb** [comment]
@GithubberSD I have the same issue and unfortunately this didn't work for me

**Comment by GithubberSD** [comment]
@lukesb, did you clean the DB? And it is also not working when you insert the 2nd person?

The error which is thrown is a general error (Error: SQLSTATE[23000]), converted to the error "Username or email already exists". So maybe something else is wrong.

The solution i gave is working fine for me.

**Comment by lukesb** [comment]
@GithubberSD No, I didn't. What  do you mean by clean the db? Start again or just clear out the data?

**Comment by GithubberSD** [comment]
Yes, clear out the data.

**Comment by lukesb** [comment]
Ok, I will try that and let you know. Thanks very much for your help

**Comment by arneessa** [comment]
I modified "login/createuser.php" to "$response = $a->createUser($newuser, $newid, $_POST['email'], $newpw);" i did completely empty the database and restarted the computer (Macbook 2016) but the problem is still the same.
do anyone have a suggestion for installing some "tracers" so I can identify where the problem is??

**Comment by GithubberSD** [comment]
Too bad... Then i dont know what is going wrong. The data seems to be duplicated.  
You can check which data is inserted in the database by for example using the console log (F12 in the browser).

First you have to put some code before the insert statement which you modified (createUser). You also can create a function for this, but for the quick win, try this:

echo "<script>console.log( 'Debug Objects: " . $newuser . "' );</script>";
echo "<script>console.log( 'Debug Objects: " . $newid . "' );</script>";
echo "<script>console.log( 'Debug Objects: " . $_POST['email'] . "' );</script>";
echo "<script>console.log( 'Debug Objects: " . $newpw . "' );</script>";

Then create a new user and check in the console log which data is inserted in the database en which data is duplicated. Maybe now you know why its going wrong.

Delete the code when you fixed it.
