### ISSUE TITLE
not getting emails

### ISSUE THREAD

**Issue by ad221282** [therecluse26/PHP-Login#95]
Hi, the zip that I download does not have the php mailer autoload, anyway I fix that, so far I can create users, but i am not getting the emails in order to verify the accoint and log in, help please, what I may doing wrong?

**Comment by kumaunix** [comment]
I have the same problem, Im configuring a admin email using a gmail account pls help

**Comment by ad221282** [comment]
I fix it, add me on facebook ad221282@gmail.com so I can help you directly! My email server is up and running without any problem now!

**Comment by kumaunix** [comment]
Thanks perhaps you can put it up here so others can read it is that okay?

**Comment by kumaunix** [comment]
did you edit the config.php file correctly? if yes what are the configuration of your config.php file? please share

**Comment by ad221282** [comment]
Give me a few minutes to see how to share those files, the php mailer is incomplete in this zip folder , and on Gmail you can receive but can't send to Gmail, hotmail or Yahoo! Because you need 
1 have an business IP address 
2 you have to encrypt your server in order to send to those mails accounts

**Comment by ad221282** [comment]
I'll connect in my pc in a while and upload those file and the while solution to  this!

**Comment by kumaunix** [comment]
thanks man, I really appreciate it. Looking forward for your response and your advice

**Comment by ad221282** [comment]
Sorry my bad, I thought this was a thread for round cube, so what's your problem again!
Not getting emails?

**Comment by ad221282** [comment]
first what kind of email server are You using to send the mail responses?

**Comment by ad221282** [comment]
let me know or add me on facebook or messenger for a fast solution!

**Comment by ad221282** [comment]
ok I remember now, i have to open my files and check my server to remember, the first error I did have was that the php mailer was empty in the /login/scripts/phpmailer , let me know if you have that already or if you need that file first, then we do the second step!

**Comment by ad221282** [comment]
I'll wait here if need me

**Comment by kumaunix** [comment]
add me on messenger
 Tobias Sopu

**Comment by kumaunix** [comment]
or email me is better 
tobias.sopu@gmail.com

**Comment by ad221282** [comment]
I add you on messenger, waiting for your response

**Comment by kumaunix** [comment]
Again : when new user register, no email is sent for verification before they could log in. according to the SQL if verified column is still 0, user cannot log in. I think when user verify, it changes to 1 before they could login it. but the email is not sent inorder to verify

**Comment by ad221282** [comment]
send me the link to your pagetest!

**Comment by ad221282** [comment]
https://sitio1.ecsignsla.com/login/signup.php
this is mine and is just the main page you can check and we star from there!
