### ISSUE TITLE
Timezone not set causing apparent login hang

### ISSUE THREAD

**Issue by sreed4** [therecluse26/PHP-Login#98]
I was having a problem with the login hanging with the wait icon spinning forever.  Turns out the problem was PHP was issuing the warning the the timezone must be set and then sending the json for the user login success.  Putting 
`date_default_timezone_set("America/Indianapolis");`
as the first statement in config.php everything started to work.

**Comment by therecluse26** [comment]
Good catch! I'll have to add that to the config options.
